import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { CalendarClock, Brain, Target, Trophy, Zap, BookOpenCheck, CheckCircle2 } from "lucide-react";
import type { SetWithCards } from "@/lib/queries";
import { computeProgress } from "@/lib/progress";
import { getSessionHistory } from "./SessionHistory";
import { addXp } from "@/lib/gamification";
import { toast } from "sonner";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Props = { sets: SetWithCards[] };
const inputClass = "w-full rounded-lg border border-line bg-accent px-3 py-2 text-sm";
const panel = "rounded-2xl border border-line bg-panel p-5 md:p-6";

export function StudyCommandSuite({ sets }: Props) {
  const [examDates, setExamDates] = useState<Record<string, string>>(() => { try { return JSON.parse(localStorage.getItem("momentum_exam_dates_v1") || "{}"); } catch { return {}; } });
  const [completed, setCompleted] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("momentum_challenges_v1") || "[]"); } catch { return []; } });
  const [challenge, setChallenge] = useState("recall");
  const exams = sets.map((s) => ({ set: s, date: examDates[s.id] || s.exam_date || "" })).filter((x) => x.date).sort((a,b) => a.date.localeCompare(b.date));
  const mastery = sets.map((s) => ({ set: s, p: computeProgress(s.flashcards, s.quiz_score, s.quiz_total) })).sort((a,b) => a.p.overall-b.p.overall);
  const sessions = useMemo(() => getSessionHistory().filter((s) => !s.id.startsWith("sess_demo_")), []);
  const minutes = sessions.reduce((sum, s) => sum + (Number(String(s.duration).match(/[\d.]+/)?.[0]) || 0), 0);
  const focusScore = Math.min(100, Math.round((Math.min(minutes / 180, 1) * 35) + (Math.min(sessions.length / 8, 1) * 25) + (Math.min(new Set(sessions.map(s => new Date(s.timestamp).toDateString())).size / 5, 1) * 25) + (sessions.length ? 15 : 0)));
  const today = new Date(); today.setHours(0,0,0,0);
  const saveDate = (id: string, date: string) => { const next = { ...examDates, [id]: date }; setExamDates(next); localStorage.setItem("momentum_exam_dates_v1", JSON.stringify(next)); };
  const toggleChallenge = (id: string, xp: number) => { if (completed.includes(id)) return; const next = [...completed, id]; setCompleted(next); localStorage.setItem("momentum_challenges_v1", JSON.stringify(next)); addXp(xp); toast.success(`Challenge complete · +${xp} XP`); };
  const challenges = [{ id:"recall", title:"Recall Sprint", detail:"Review 15 flashcards without looking at the answers first.", reward:"60 XP", xp:60 }, { id:"weak", title:"Weak-Topic Boss", detail:"Spend one focused session on your lowest-mastery set.", reward:"100 XP", xp:100 }, { id:"perfect", title:"Clean Sweep", detail:"Finish a quiz and aim for a personal-best score.", reward:"80 XP", xp:80 }];
  const activeChallenge = challenges.find((c) => c.id === challenge)!;

  return <div className="space-y-5">
    <Tabs defaultValue="exam">
      <TabsList className="w-full justify-start overflow-x-auto bg-panel border border-line"><TabsTrigger value="exam">Exam mode</TabsTrigger><TabsTrigger value="mastery">Mastery</TabsTrigger><TabsTrigger value="focus">Focus & challenges</TabsTrigger><TabsTrigger value="mistakes">Mistakes & achievements</TabsTrigger></TabsList>
      <TabsContent value="exam" className="space-y-5">
        <section className={panel}><div className="flex items-start gap-3"><div className="rounded-xl bg-cool/10 p-2 text-cool2"><CalendarClock className="size-5"/></div><div><h2 className="font-display text-xl font-bold">Exam mode</h2><p className="text-sm text-soft mt-1">Give each course an exam date. Momentum keeps the countdown and current readiness together.</p></div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3 mt-5">{sets.map(s => { const date = examDates[s.id] || s.exam_date || ""; const days = date ? Math.ceil((new Date(date+"T00:00:00").getTime()-today.getTime())/86400000) : null; const p = computeProgress(s.flashcards,s.quiz_score,s.quiz_total); return <div key={s.id} className="rounded-xl border border-line bg-accent p-4"><div className="font-semibold">{s.name}</div><div className="text-xs text-soft mt-1">{s.subject || "Study set"} · {p.overall}% current progress</div><label className="block text-xs text-soft mt-3 mb-1">Exam date</label><input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>saveDate(s.id,e.target.value)} className={inputClass}/>{days !== null && <p className="text-sm font-semibold text-cool2 mt-3">{days < 0 ? "Date passed" : days === 0 ? "Exam day" : `${days} days remaining`} · {p.overall}% readiness</p>}<Link to="/sets/$id" params={{id:s.id}} search={{tab:"plan"}} className="inline-flex mt-3 text-sm font-semibold text-cool2 hover:underline">Open full study plan →</Link></div>})}</div>{exams.length === 0 && <p className="text-xs text-soft mt-3">Add an exam date to activate a countdown.</p>}</section>
      </TabsContent>
      <TabsContent value="mastery"><section className={panel}><div className="flex items-start gap-3"><Brain className="size-5 text-cool2 mt-1"/><div><h2 className="font-display text-xl font-bold">Mastery map</h2><p className="text-sm text-soft mt-1">Lowest-progress subjects rise to the top so you know where effort matters most.</p></div></div><div className="mt-5 space-y-4">{mastery.map(({set,p})=><div key={set.id}><div className="flex justify-between gap-3 text-sm"><Link to="/sets/$id" params={{id:set.id}} className="font-semibold hover:text-cool2">{set.name}</Link><span>{p.overall}%</span></div><div className="h-2 rounded-full bg-foreground/10 mt-2 overflow-hidden"><div className="h-full rounded-full bg-progress" style={{width:`${p.overall}%`}}/></div><div className="text-xs text-soft mt-1">{p.mastered} of {p.total} cards mastered{p.quizPct != null ? ` · quiz ${p.quizPct}%` : ""}</div></div>)}</div></section></TabsContent>
      <TabsContent value="focus" className="grid lg:grid-cols-2 gap-5"><section className={panel}><div className="flex items-center gap-2"><Target className="size-5 text-cool2"/><h2 className="font-display text-xl font-bold">Focus score</h2></div><div className="flex items-end gap-3 mt-4"><span className="font-display text-5xl font-bold text-cool2">{focusScore}</span><span className="text-sm text-soft mb-1">/100 · consistency</span></div><div className="h-2 bg-foreground/10 rounded-full overflow-hidden mt-3"><div className="h-full bg-progress rounded-full" style={{width:`${focusScore}%`}}/></div><div className="grid grid-cols-3 gap-2 mt-4 text-center"><div className="rounded-lg bg-accent p-3"><div className="font-display text-lg">{sessions.length}</div><div className="text-[10px] text-soft">sessions</div></div><div className="rounded-lg bg-accent p-3"><div className="font-display text-lg">{Math.round(minutes)}m</div><div className="text-[10px] text-soft">focus</div></div><div className="rounded-lg bg-accent p-3"><div className="font-display text-lg">{new Set(sessions.map(s=>new Date(s.timestamp).toDateString())).size}</div><div className="text-[10px] text-soft">active days</div></div></div><p className="text-xs text-soft mt-3">A consistency indicator based on logged sessions, not a measurement of actual attention.</p></section><section className={panel}><div className="flex items-center gap-2"><Zap className="size-5 text-amber-300"/><h2 className="font-display text-xl font-bold">Challenge mode</h2></div><p className="text-sm text-soft mt-1">Short goals that turn practice into a game without hiding the real study work.</p><select value={challenge} onChange={e=>setChallenge(e.target.value)} className={`${inputClass} mt-4`}>{challenges.map(c=><option key={c.id} value={c.id}>{c.title} · {c.reward}</option>)}</select><div className="mt-3 rounded-xl bg-accent border border-line p-4"><div className="flex justify-between gap-3"><h3 className="font-semibold">{activeChallenge.title}</h3><span className="text-xs text-cool2 font-semibold">{activeChallenge.reward}</span></div><p className="text-sm text-soft mt-2">{activeChallenge.detail}</p><button onClick={()=>toggleChallenge(activeChallenge.id,activeChallenge.xp)} className="mt-3 rounded-lg border border-line px-3 py-2 text-sm font-semibold flex items-center gap-2">{completed.includes(activeChallenge.id)?<CheckCircle2 className="size-4 text-emerald-400"/>:<Zap className="size-4"/>}{completed.includes(activeChallenge.id)?"Completed · XP awarded":"Complete challenge · claim XP"}</button></div></section></TabsContent>
      <TabsContent value="mistakes" className="space-y-5"><section className={panel}><div className="flex items-center gap-2"><BookOpenCheck className="size-5 text-cool2"/><h2 className="font-display text-xl font-bold">Mistake intelligence</h2></div><p className="text-sm text-soft mt-1">Turn missed questions into a repair loop: understand the mistake, then retest the same concept with fresh wording.</p><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3 mt-4">{sets.map(s=><div key={s.id} className="rounded-xl border border-line bg-accent p-3"><p className="font-semibold text-sm">{s.name}</p><p className="text-xs text-soft mt-1">Use the set's Mistake Bank to review repeated misses, explanations and similar questions.</p><Link to="/sets/$id" params={{id:s.id}} search={{tab:"mistakes"}} className="inline-block text-sm text-cool2 font-semibold mt-3">Review mistakes →</Link></div>)}</div></section><section className={panel}><div className="flex items-center gap-2"><Trophy className="size-5 text-amber-300"/><h2 className="font-display text-xl font-bold">Achievement cabinet</h2></div><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3 mt-4">{[{name:"First Steps",desc:"Create your first study set",done:sets.length>0},{name:"Card Collector",desc:"Have 50+ flashcards",done:sets.reduce((n,s)=>n+s.flashcards.length,0)>=50},{name:"Exam Planner",desc:"Set an exam date",done:exams.length>0},{name:"Consistent Learner",desc:"Study on 5 different days",done:new Set(sessions.map(s=>new Date(s.timestamp).toDateString())).size>=5}].map(a=><div key={a.name} className={`rounded-xl border p-4 ${a.done?"border-amber-300/40 bg-amber-300/5":"border-line bg-accent opacity-75"}`}><Trophy className={`size-5 ${a.done?"text-amber-300":"text-soft"}`}/><p className="font-semibold mt-2">{a.name}</p><p className="text-xs text-soft mt-1">{a.desc}</p><p className={`text-[11px] font-semibold mt-3 ${a.done?"text-emerald-400":"text-soft"}`}>{a.done?"Unlocked":"In progress"}</p></div>)}</div></section></TabsContent>
    </Tabs>
  </div>;
}
