/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamRouteImport } from './routes/_authenticated/exam'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedAssignmentIndexRouteImport } from './routes/_authenticated/assignment.index'
import { Route as AuthenticatedAssignmentIdRouteImport } from './routes/_authenticated/assignment.$id'
import { Route as AuthenticatedEssayIndexRouteImport } from './routes/_authenticated/essay.index'
import { Route as AuthenticatedEssayIdRouteImport } from './routes/_authenticated/essay.$id'
import { Route as AuthenticatedSetsIdRouteImport } from './routes/_authenticated/sets.$id'
import { Route as AuthenticatedSetsNewRouteImport } from './routes/_authenticated/sets.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamRoute = AuthenticatedExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssignmentIndexRoute =
  AuthenticatedAssignmentIndexRouteImport.update({
    id: '/assignment/',
    path: '/assignment/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentIdRoute =
  AuthenticatedAssignmentIdRouteImport.update({
    id: '/assignment/$id',
    path: '/assignment/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEssayIndexRoute = AuthenticatedEssayIndexRouteImport.update({
  id: '/essay/',
  path: '/essay/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEssayIdRoute = AuthenticatedEssayIdRouteImport.update({
  id: '/essay/$id',
  path: '/essay/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetsIdRoute = AuthenticatedSetsIdRouteImport.update({
  id: '/sets/$id',
  path: '/sets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetsNewRoute = AuthenticatedSetsNewRouteImport.update({
  id: '/sets/new',
  path: '/sets/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/search': typeof AuthenticatedSearchRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/assignment/$id': typeof AuthenticatedAssignmentIdRoute
  '/essay/$id': typeof AuthenticatedEssayIdRoute
  '/sets/$id': typeof AuthenticatedSetsIdRoute
  '/sets/new': typeof AuthenticatedSetsNewRoute
  '/assignment/': typeof AuthenticatedAssignmentIndexRoute
  '/essay/': typeof AuthenticatedEssayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/search': typeof AuthenticatedSearchRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/assignment/$id': typeof AuthenticatedAssignmentIdRoute
  '/essay/$id': typeof AuthenticatedEssayIdRoute
  '/sets/$id': typeof AuthenticatedSetsIdRoute
  '/sets/new': typeof AuthenticatedSetsNewRoute
  '/assignment': typeof AuthenticatedAssignmentIndexRoute
  '/essay': typeof AuthenticatedEssayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam': typeof AuthenticatedExamRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/assignment/$id': typeof AuthenticatedAssignmentIdRoute
  '/_authenticated/essay/$id': typeof AuthenticatedEssayIdRoute
  '/_authenticated/sets/$id': typeof AuthenticatedSetsIdRoute
  '/_authenticated/sets/new': typeof AuthenticatedSetsNewRoute
  '/_authenticated/assignment/': typeof AuthenticatedAssignmentIndexRoute
  '/_authenticated/essay/': typeof AuthenticatedEssayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/exam'
    | '/history'
    | '/search'
    | '/trash'
    | '/api/transcribe'
    | '/assignment/$id'
    | '/essay/$id'
    | '/sets/$id'
    | '/sets/new'
    | '/assignment/'
    | '/essay/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coach'
    | '/dashboard'
    | '/exam'
    | '/history'
    | '/search'
    | '/trash'
    | '/api/transcribe'
    | '/assignment/$id'
    | '/essay/$id'
    | '/sets/$id'
    | '/sets/new'
    | '/assignment'
    | '/essay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam'
    | '/_authenticated/history'
    | '/_authenticated/search'
    | '/_authenticated/trash'
    | '/api/transcribe'
    | '/_authenticated/assignment/$id'
    | '/_authenticated/essay/$id'
    | '/_authenticated/sets/$id'
    | '/_authenticated/sets/new'
    | '/_authenticated/assignment/'
    | '/_authenticated/essay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam': {
      id: '/_authenticated/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthenticatedExamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assignment/': {
      id: '/_authenticated/assignment/'
      path: '/assignment'
      fullPath: '/assignment/'
      preLoaderRoute: typeof AuthenticatedAssignmentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignment/$id': {
      id: '/_authenticated/assignment/$id'
      path: '/assignment/$id'
      fullPath: '/assignment/$id'
      preLoaderRoute: typeof AuthenticatedAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/essay/': {
      id: '/_authenticated/essay/'
      path: '/essay'
      fullPath: '/essay/'
      preLoaderRoute: typeof AuthenticatedEssayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/essay/$id': {
      id: '/_authenticated/essay/$id'
      path: '/essay/$id'
      fullPath: '/essay/$id'
      preLoaderRoute: typeof AuthenticatedEssayIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sets/$id': {
      id: '/_authenticated/sets/$id'
      path: '/sets/$id'
      fullPath: '/sets/$id'
      preLoaderRoute: typeof AuthenticatedSetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sets/new': {
      id: '/_authenticated/sets/new'
      path: '/sets/new'
      fullPath: '/sets/new'
      preLoaderRoute: typeof AuthenticatedSetsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamRoute: typeof AuthenticatedExamRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedAssignmentIdRoute: typeof AuthenticatedAssignmentIdRoute
  AuthenticatedEssayIdRoute: typeof AuthenticatedEssayIdRoute
  AuthenticatedSetsIdRoute: typeof AuthenticatedSetsIdRoute
  AuthenticatedSetsNewRoute: typeof AuthenticatedSetsNewRoute
  AuthenticatedAssignmentIndexRoute: typeof AuthenticatedAssignmentIndexRoute
  AuthenticatedEssayIndexRoute: typeof AuthenticatedEssayIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamRoute: AuthenticatedExamRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedAssignmentIdRoute: AuthenticatedAssignmentIdRoute,
  AuthenticatedEssayIdRoute: AuthenticatedEssayIdRoute,
  AuthenticatedSetsIdRoute: AuthenticatedSetsIdRoute,
  AuthenticatedSetsNewRoute: AuthenticatedSetsNewRoute,
  AuthenticatedAssignmentIndexRoute: AuthenticatedAssignmentIndexRoute,
  AuthenticatedEssayIndexRoute: AuthenticatedEssayIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
